### ISSUE TITLE
🐛 BUG discovered when trying to add available GitHub profile links to officers/devs on the `/Team` page

### ISSUE THREAD

**Issue by KemingHe** [devosu/dev-website#6]
Discovered bug that will style/render links to blue blobs, see #7, same screenshot is also commented here for convenience. (Edit: grammar)

**Comment by KemingHe** [comment]
![Style conflict with adding links](https://github.com/devosu/dev-website/assets/44534763/50e5e4ca-156b-480e-a69a-f87afaaf493d)
@GulkoA @mjgusev

**Comment by gulkoa** [comment]
Gradient text shouldn't be a link by design, because it would look overwhelming, so I propose putting relevant links next to the name inline. I refactored iconTextLink shortcode in PR #9 and included an example of how I think it should be done on @KemingHe 's github
